stages:
  - plan
  - apply
  - destroy

before_script:
  - wget https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip
  - unzip terraform_1.0.8_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - terraform init -backend-config="bucket=store-infra-state-eem" -backend-config="key=terraform.tfstate"

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
  # only:
  #   - feature-branch-name

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  when: manual
  allow_failure: true
  # only:
  # - feature-branch-name

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  AWS_DEFAULT_REGION: "ap-southeast-1"

destroy:
  stage: destroy
  script:
    - terraform init -backend-config="bucket=store-infra-state-eem" -backend-config="key=terraform.tfstate"
    - terraform destroy -auto-approve
  when: manual
  allow_failure: true
  # only:
  #   - feature-branch-name
