name: Terraform Workflow

on:
  push:
    branches:
      - main  # Adjust to your main branch name or desired trigger branch
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-1

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Download Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip
          unzip terraform_1.0.8_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
      
      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=store-infra-state-eem" -backend-config="key=terraform.tfstate"
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1
      
      - name: Save Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Download Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip
          unzip terraform_1.0.8_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1
      
  destroy:
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Download Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip
          unzip terraform_1.0.8_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
      
      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=store-infra-state-eem" -backend-config="key=terraform.tfstate"
      
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1
